Add custom classes for private and grade comments
livinglab/wp-grade-comments pull request #17
Opened 2019-12-17 09:20 UTC by Mamaduka

Following classes are enough to better navigate grade comment DOM elements.

@boonebgorges  can we get this merged for version 1.4?

2019-12-17 15:58 UTC, boonebgorges requested changes
Yup, the technique looks good and we can definitely do it. Could we please make the following changes to the new classes to make the semantics clearer? `comment-is-private` and `comment-has-grade`

2019-12-18 08:41 UTC, Mamaduka commented
Updated classes as requested.

2019-12-18 16:03 UTC, boonebgorges approved these changes

2019-12-18 16:03 UTC, boonebgorges commented
LGTM

2019-12-18 16:03 UTC, merged